package com.kpmg.core.workflow.constants;

import com.kpmg.core.annotations.WorkflowCodeExcludeFromCodeCoverageReportGenerated;

/** This class is for all workflow related constants. */
@WorkflowCodeExcludeFromCodeCoverageReportGenerated
public final class WorkflowConstants {

  public static final String PROCESS_LABEL = "process.label";
  public static final String CHOOSER_LABEL = "chooser.label";
  public static final String AUDIT_LOG_PATH = "/var/audit";
  public static final String AUDIT_LOG_REPLICATION = "com.day.cq.replication";
  public static final String TYPE_JCR_PATH = "JCR_PATH";
  public static final String JCR_CONTENT = "/jcr:content";
  public static final String SLASH = "/";
  public static final String SPLIT_PERIOD = "\\.";
  public static final String PROCESS_ARGS = "PROCESS_ARGS";
  public static final String JCR_PATH = "JCR_PATH";
  public static final String JCR_UUID = "JCR_UUID";
  public static final String MAJOR = "major";
  public static final String MINOR = "minor";
  public static final String ABSOLUTE_TIME = "absoluteTime";
  public static final String REVIEWER_GROUP = "reviewerGroup";
  public static final String ADMINISTRATORS = "administrators";
  public static final String CREATEDBY = "CREATEDBY";
  public static final String GLOBAL_SITE_ADMINISTRATORS = "aem-global-site-administrators";

  public static final String CQ_LIVE_RELATIONSHIP = "cq:LiveRelationship";
  public static final String BLUEPRINT_CONTRIBUTORS = "blueprint-contributors";
  public static final String DEFAULT_SENDER_EMAIL_ADDRESS_LABEL = "KPMG";
  public static final String CONFIRM_ACTIVATION = "confirmActivation";

  public static final String MODEL_TITLE = "modelTitle";
  public static final String PAYLOAD = "payload";
  public static final String MESSAGE1 = "message1";
  public static final String MESSAGE2 = "message2";
  public static final String MESSAGE3 = "message3";
  public static final String HOST_PREFIX = "host.prefix";
  public static final String REVIEW_USER = "reviewUser";
  public static final String ACTIVATED = "activated";
  public static final String ACTIVATION_COMPLETE = "activationIncomplete";
  public static final String KPMG_WORKFLOW_VIEWINBOX = "kpmg.workflow.viewInboxText";
  public static final String VIEWINBOX = "viewInboxText";
  public static final String KPMG_WORKFLOW_AUTOGENERATE = "kpmg.workflow.autoGeneratedText";
  public static final String AUTO_GENERATEDTEXT = "autoGeneratedText";
  public static final String WORKFLOW_TITLE = "workflowTitle";
  public static final String WORKFLOW_INITIATOR = "initiator";
  public static final String AUTOGENERATE = "autoGeneratedText";
  public static final String SUBJECT = "subject";

  public static final String APPROVAL_REQUIRED = "approval-required";
  public static final String APPROVAL_ROLLOUT_BLUE_PRINT_OWNERS = "perform-manual-rollout";
  public static final String APPROVED_ACTIVATED_FOR_INITIATOR = "approved-activated";
  public static final String APPROVED_NOT_ACTIVATED = "approved-not-activated";
  public static final String PAGE_EXPIRED = "activation-incomplete";
  public static final String PAGE_DATE_MISSING_ACTIVIATION_PERMISSION =
      "checkOnOffDateORActivationPermission";
  public static final String APPROVED_SCHEDULED_FOR_ACTIVATION = "approved-scheduled-activation";
  public static final String ROLLOUT_FOR_BLLUE_PRINT_OWNERS_FOR_ACTIVATION_WORKFLOW =
      "perform-manual-rollout-for-activation-workflow";
  public static final String NOT_ACTIVATED_EMAIL_FOR_INITIATOR = "notActivated";
  public static final String ACTIVATED_EMAIL_FOR_INITIATOR = "activated";
  public static final String DEACTIVATION_APPROVER_NOTIFICATION =
      "deactivationApproverNotification";
  public static final String DEACTIVATION_SITEADMIN_NOTIFICATION =
      "deactivationSiteAdminNotification";
  public static final String DEACTIVATION_INITIATOR_NOTIFICATION =
      "deactivationInitiatorNotification";
  public static final String FAILURE_NOTIFICATION = "failurenotification";

  public static final String DELEGATEE_EMAIL = "delegatee-email";

  public static final String STEPBACK_EMAIL = "stepback-email-intiator.txt";

  public static final String DEFAULT_FROM_ADDRESS_LABEL = "KPMG";
  public static final String CC_LIST_IS_EMPTY = "ccEmail list is empty ";
  public static final String TO_EMAIL_LIST_IS_EMPTY = "ToEmail list is empty";
  public static final String EMAIL_NOTIFICATION_DISABLED = "Email Notification Disabled";
  public static final String ERROR_IN_SENDING_EMAIL = "Error in sending email";
  public static final String UTF_8 = "UTF-8";
  public static final String EMAIL = "email";
  public static final String HIDE_IN_SEARCH = "hideInSearch";

  public static final String ACTIVATION_ON_COMPLETE = "activateOnCompletion";
  public static final String FALSE = "false";
  public static final int DEPTH = 3;
  public static final String SITE_SETTINGS_PAGE = "/admin/blog-site-settings";
  public static final String NODE_PROPERTY = "value";
  public static final String NODE_NAME = "i18NLocale";
  public static final String AEM_GROUPS_PREFIX = "aem-";

  private WorkflowConstants() {}
}
