on:
  push:
    branches:
      - develop
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:kpmg-interim/KPMG.com.git"
          source_branch: develop
          destination_repo: "https://${{ env.CM_USER_NAME }}:${{ secrets.CM_ACCESS_TOKEN }}@git.cloudmanager.adobe.com/kpmg/kpmg-dot-com/"
          destination_branch: develop
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}